// Generated by https://quicktype.io

/**
 * Response Release Model
 */
export interface RepositoryRelease {
    url:              string;
    html_url:         string;
    assets_url:       string;
    upload_url:       string;
    tarball_url:      string;
    zipball_url:      string;
    id:               number;
    node_id:          string;
    tag_name:         string;
    target_commitish: string;
    name:             string;
    body:             string;
    draft:            boolean;
    prerelease:       boolean;
    created_at:       string;
    published_at:     string;
    author:           Author;
    assets:           Asset[];
}

/**
 * Response Release Author Model
 */
export interface Author {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
}

/**
 * Response Release Asset Model
 */
export interface Asset {
    url:                  string;
    browser_download_url: string;
    id:                   number;
    node_id:              string;
    name:                 string;
    label:                string;
    state:                string;
    content_type:         string;
    size:                 number;
    download_count:       number;
    created_at:           string;
    updated_at:           string;
    uploader:             Uploader;
}

/**
 * Repository Release Assets Uploader Model
 */
export interface Uploader {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
}


// Generated by https://quicktype.io

/**
 * Github Repository API Basic
 */
export abstract class GitHubRepositoryApi {
    owner: string;
    repo: string;

    abstract toUrl ();
    abstract send ();
}

/**
 * Repository Relase List API
 */
export class RepositoryReleaseListApi extends GitHubRepositoryApi {
    send() {
        throw new Error("Method not implemented.");
    }
    toUrl() {
        return `/repos/${this.owner}/${this.repo}/releases`;
    }
}

/**
 * Repository Release Create Input Interface
 */
export interface RepositoryReleaseCreateInputInfo {
    tag_name:         string;
    target_commitish: string;
    name:             string;
    body:             string;
    draft:            boolean;
    prerelease:       boolean;
}

/**
 * Repository Release Create API
 */
export class RepositoryReleaseCreateApi extends GitHubRepositoryApi {
    input: RepositoryReleaseCreateInputInfo;
    send() {
        throw new Error("Method not implemented.");
    }   
    toUrl() {
        return `/repos/${this.owner}/${this.repo}/releases`;
    }
}

/**
 * Repository Release Assets Uplaod API Class
 */
export class RepositoryReleaseAssetsUploadApi extends GitHubRepositoryApi {
    upload_url: string;
    release_id: string;
    content_type: string;
    name: string;
    label?: string;
    toUrl() {
        throw new Error("Method not implemented.");
    }
    send() {
        throw new Error("Method not implemented.");
    }
}